export const FACES_DO_MATCH = 'FACES_DO_MATCH';
export const FACES_NOT_MATCH = 'FACES_NOT_MATCH';

export const FAILED_VERIFICATION = 'FAILED_VERIFICATION';
export const ERROR_STATE = 'ERROR_STATE';

export const SET_ORIGINAL_TEXT = 'SET_ORIGINAL_TEXT';

export const SET_INITIAL_STATE = 'SET_INITIAL_STATE'

